import type { GameOverview } from './api/gameOverview'
import { officialArtworkUrl } from './officialArtwork'

// All URLs are generated by Vite from checked-in public game artwork.
const files = import.meta.glob<string>(['../assets/skland/*.png', '../assets/skland/*.avif'], {
  eager: true,
  query: '?url&no-inline',
  import: 'default',
})
export type OverviewArt = {
  src: string
  presentation?: 'official-logo' | 'official-title-icon'
  tone: 'light-ink' | 'dark-ink' | 'color'
  kind: 'icon' | 'map' | 'landscape' | 'cover'
  fallback?: OverviewArt
}
// Only neutral UI symbols may invert. Medal tiers, room colors and map artwork
// carry game semantics and must keep their original colors.
const colorIcons = new Set([
  'ak-logoBase',
  'ak-logoResist',
  'ak-main-task-over',
  'ak-day-common',
  'ak-day-challenge',
  'ef-control',
  'ef-glory-certify',
  'ef-build-domain_1',
  'ef-build-domain_2',
  'ef-bill-domain_1',
  'ef-bill-domain_2',
  'ef-stock-empty',
  'ef-stock-full',
  'ef-monolith-unearned',
  'ef-manufacture',
  'ef-plant',
  'ef-reception',
  'ef-medalLevel1',
  'ef-medalLevel2',
  'ef-medalLevel3',
])
const art = (key: string, kind: OverviewArt['kind'] = 'icon'): OverviewArt | undefined => {
  const src = files[`../assets/skland/${key}.png`] ?? files[`../assets/skland/${key}.avif`]
  return src
    ? {
        src,
        kind,
        presentation: key.startsWith('ak-title-')
          ? 'official-title-icon'
          : key === 'ak-logoBase'
            ? 'official-logo'
            : undefined,
        tone:
          kind !== 'icon' ||
          colorIcons.has(key) ||
          key.startsWith('ef-war-') ||
          key.startsWith('ef-growth-')
            ? 'color'
            : key.startsWith('ak-') || key === 'ef-regionalDevelopment'
              ? 'light-ink'
              : 'dark-ink',
      }
    : undefined
}
export const growthArt = (id: string) => art(`ef-growth-${id}`)
const akMetrics: Record<string, string> = {
  stamina: 'icon-ap',
  training: 'icon-training',
  daily: 'icon-routineDaily',
  weekly: 'icon-routineWeekly',
  orundum: 'icon-campaignReward',
  drones: 'icon-labor',
  tradingOrders: 'icon-trading',
  tiredOperators: 'icon-tiredChars',
  recruitRefresh: 'icon-hire',
  operators: 'char',
  skins: 'skin',
  furniture: 'furniture',
  medals: 'medal',
  manufacturing: 'icon-manufacture',
  restedOperators: 'icon-dormitory',
  clueCollection: 'icon-meeting',
  recruitAvailable: 'icon-recruit',
  towerLower: 'icon-towerRewardLower',
  towerHigher: 'icon-towerRewardHigher',
}
const efMetrics: Record<string, string> = {
  stamina: 'stamina',
  activity: 'activity',
  weekly: 'weekly',
  battlePass: 'battlePass',
  achievements: 'achievements',
  ether: 'ether',
  chests: 'chests',
  pieces: 'pieces',
  seekSuspicion: 'seekSuspicion',
  medalLevel1: 'medalLevel1',
  medalLevel2: 'medalLevel2',
  medalLevel3: 'medalLevel3',
  cnsLevel: 'control',
}
export function metricArt(game: string, key: string) {
  const id =
    game === 'arknights' ? akMetrics[key] : game === 'endfield' ? efMetrics[key] : undefined
  return id ? art(`${game === 'arknights' ? 'ak' : 'ef'}-${id}`) : undefined
}
const sections: Record<string, string> = {
  arknightsDaily: 'ak-title-daily',
  arknightsBase: 'ak-title-base',
  arknightsRecruitment: 'ak-icon-recruit',
  arknightsOffice: 'ak-icon-hire',
  arknightsTraining: 'ak-icon-training',
  arknightsManufacturing: 'ak-icon-manufacture',
  arknightsDormitories: 'ak-icon-dormitory',
  arknightsClues: 'ak-icon-meeting',
  arknightsTrading: 'ak-icon-trading',
  arknightsSupport: 'ak-char',
  arknightsActivities: 'ak-sideStory',
  arknightsRogue: 'ak-integratedStrategies',
  arknightsRogueRelics: 'ak-integratedStrategies',
  arknightsRogueBank: 'ak-integratedStrategies',
  arknightsTower: 'ak-icon-towerRewardHigher',
  arknightsCampaign: 'ak-icon-campaignReward',
  arknightsSandbox: 'ak-logoBase',
  arknightsBossRush: 'ak-bossRush',
  endfieldSpaceship: 'ef-spaceship',
  endfieldExploration: 'ef-regionExplore',
  endfieldExplorationPuzzles: 'ef-ether',
  endfieldExplorationChests: 'ef-chests',
  endfieldExplorationPieces: 'ef-pieces',
  endfieldExplorationBlackboxes: 'ef-blackboxes',
  endfieldExplorationEquipChests: 'ef-equipChests',
  endfieldExplorationTrstars: 'ef-trstars',
  endfieldWarEchoes: 'ef-warEchoes',
  endfieldWarEchoesWeeks: 'ef-warEchoes',
  endfieldWarEchoesStages: 'ef-warEchoes',
  endfieldMonolith: 'ef-monolith',
  endfieldDomains: 'ef-regionalDevelopment',
}
export const sectionArt = (key: string) => (sections[key] ? art(sections[key]!) : undefined)
const sandboxMilestones = {
  baseLv: 'ak-logoBase',
  unlockNode: 'ak-logoExplore',
  enemyKill: 'ak-logoResist',
  createRift: 'ak-logoRecord',
} as const
export const sandboxMilestoneArt = (key: keyof typeof sandboxMilestones) =>
  art(sandboxMilestones[key])
export const sandboxDayArt = (key: 'maxDay' | 'maxDayChallenge') =>
  art(key === 'maxDay' ? 'ak-day-common' : 'ak-day-challenge')
export const sandboxChapterArt = (chapter: number | 'over') => art(`ak-main-task-${chapter}`)
const rooms: Record<string, string> = {
  endfieldControl: 'control',
  endfieldManufacture1: 'manufacture',
  endfieldManufacture2: 'manufacture',
  endfieldManufacture: 'manufacture',
  endfieldPlant1: 'plant',
  endfieldPlant: 'plant',
  endfieldReception: 'reception',
}
type SectionItem = NonNullable<GameOverview['sections']>[number]['items'][number]
function localFacilityArt(
  section: string,
  item: Pick<SectionItem, 'id' | 'nameKey' | 'operatorId'>,
) {
  if (item.operatorId) return undefined
  if (section === 'endfieldSpaceship')
    return rooms[item.nameKey ?? ''] ? art(`ef-${rooms[item.nameKey!]}`) : undefined
  if (section.startsWith('endfieldExploration')) {
    const id = item.id.split(':')[1]
    // indie_dg007 shares the official map02_lv004 artwork; unknown IDs remain text-only.
    return id ? art(`ef-${id === 'indie_dg007' ? 'map02_lv004' : id}`, 'map') : undefined
  }
  if (section === 'endfieldDomains' || section === 'endfieldSettlements') {
    const id = item.id.split(':')[0]
    return id === 'domain_1' || id === 'domain_2' ? art(`ef-${id}`, 'landscape') : undefined
  }
  const variant =
    section === 'arknightsTower'
      ? 'climb_tower/icon'
      : section === 'arknightsCampaign'
        ? 'campaign/zone_icon'
        : null
  if (variant && item.id)
    return {
      src: `https://web.hycdn.cn/arknights/game/assets/game_mode/${variant}/${encodeURIComponent(item.id)}.png`,
      kind: 'icon' as const,
      tone: 'light-ink' as const,
    }
  return sectionArt(section)
}

// The upstream item owns its cover; local ID maps and section symbols are fallbacks.
export function facilityArt(
  section: string,
  item: Pick<SectionItem, 'id' | 'nameKey' | 'operatorId' | 'artworkUrl'>,
): OverviewArt | undefined {
  if (item.operatorId) return undefined
  const generic = sectionArt(section)
  const local = localFacilityArt(section, item)
  const fallback = local
    ? { ...local, fallback: local.src !== generic?.src ? generic : undefined }
    : generic
  const src = officialArtworkUrl(item.artworkUrl)
  return src ? { src, kind: 'cover', tone: 'color', fallback } : fallback
}

export const warEchoesArt = (key: string) => {
  const image = art(`ef-war-${key}`)
  return image && /^star-[0-3]$/.test(key) ? { ...image, tone: 'light-ink' as const } : image
}

export const developmentArt = (key: string) => art(`ef-${key}`)

// Official Endfield CharElementIcon / CharPotentialIcon artwork.
const endfieldElements: Record<string, [string, string]> = {
  物理: ['physical', '#888'],
  Physical: ['physical', '#888'],
  灼热: ['fire', '#ff623d'],
  Heat: ['fire', '#ff623d'],
  电磁: ['electric', '#ffc000'],
  Electric: ['electric', '#ffc000'],
  寒冷: ['ice', '#21c6d0'],
  Cryo: ['ice', '#21c6d0'],
  自然: ['nature', '#9eda23'],
  Nature: ['nature', '#9eda23'],
}
export function endfieldPortraitBadge(
  kind: 'element' | 'potential' | 'profession',
  value: string | number | null,
) {
  if (value == null) return undefined
  if (kind === 'profession') {
    const profession = endfieldProfessions[String(value)]
    const image = profession ? art(`ef-char-profession-${profession}`) : undefined
    return image ? { ...image, tone: 'color' as const, background: '#444' } : undefined
  }
  const element = kind === 'element' ? endfieldElements[String(value)] : undefined
  if (kind === 'element' && !element) return undefined
  const image = art(`ef-char-${kind}-${element?.[0] ?? value}`)
  return image ? { ...image, tone: 'color' as const, background: element?.[1] } : undefined
}

const endfieldProfessions: Record<string, string> = {
  近卫: 'guard',
  Guard: 'guard',
  重装: 'defender',
  Defender: 'defender',
  辅助: 'supporter',
  Supporter: 'supporter',
  术师: 'caster',
  Caster: 'caster',
  突击: 'striker',
  Striker: 'striker',
  先锋: 'vanguard',
  Vanguard: 'vanguard',
}

// DungeonRecordCard uses rarity, not evolvePhase, for its bottom color strip.
const endfieldRarityColors: Record<string, string> = {
  '1': '#b2b2b2',
  '2': '#b4d945',
  '3': '#33c2ff',
  '4': '#b380ff',
  '5': '#ffcc00',
  '6': '#ff7100',
}
export const endfieldRarityColor = (rarity: string | number | null | undefined) =>
  rarity == null ? undefined : endfieldRarityColors[String(rarity).replace(/^rarity_/, '')]

export const gloryArt = (kind: 'empty' | 'certify') => art(`ef-glory-${kind}`)
