import type { GameOverview } from './api/gameOverview'

// All URLs are generated by Vite from checked-in public game artwork.
const files = import.meta.glob<string>('../assets/skland/*.png', {
  eager: true,
  query: '?url&no-inline',
  import: 'default',
})
export type OverviewArt = {
  src: string
  tone: 'light-ink' | 'dark-ink' | 'color'
  kind: 'icon' | 'map' | 'landscape'
}
// Only neutral UI symbols may invert. Medal tiers, room colors and map artwork
// carry game semantics and must keep their original colors.
const colorIcons = new Set([
  'ak-logoBase',
  'ef-control',
  'ef-manufacture',
  'ef-plant',
  'ef-reception',
  'ef-medalLevel1',
  'ef-medalLevel2',
  'ef-medalLevel3',
])
const art = (key: string, kind: OverviewArt['kind'] = 'icon'): OverviewArt | undefined => {
  const src = files[`../assets/skland/${key}.png`]
  return src
    ? {
        src,
        kind,
        tone:
          kind !== 'icon' || colorIcons.has(key)
            ? 'color'
            : key.startsWith('ak-')
              ? 'light-ink'
              : 'dark-ink',
      }
    : undefined
}
const akMetrics: Record<string, string> = {
  stamina: 'icon-ap',
  daily: 'icon-routineDaily',
  weekly: 'icon-routineWeekly',
  orundum: 'icon-campaignReward',
  drones: 'icon-labor',
  tradingOrders: 'icon-trading',
  tiredOperators: 'icon-tiredChars',
  recruitRefresh: 'icon-hire',
  operators: 'char',
  skins: 'skin',
  furniture: 'furniture',
  medals: 'medal',
  manufacturing: 'icon-manufacture',
  restedOperators: 'icon-dormitory',
  recruitAvailable: 'icon-recruit',
  towerLower: 'icon-towerRewardLower',
  towerHigher: 'icon-towerRewardHigher',
}
const efMetrics: Record<string, string> = {
  stamina: 'stamina',
  activity: 'activity',
  weekly: 'weekly',
  battlePass: 'battlePass',
  achievements: 'achievements',
  ether: 'ether',
  chests: 'chests',
  pieces: 'pieces',
  seekSuspicion: 'seekSuspicion',
  medalLevel1: 'medalLevel1',
  medalLevel2: 'medalLevel2',
  medalLevel3: 'medalLevel3',
  cnsLevel: 'control',
}
export function metricArt(game: string, key: string) {
  const id =
    game === 'arknights' ? akMetrics[key] : game === 'endfield' ? efMetrics[key] : undefined
  return id ? art(`${game === 'arknights' ? 'ak' : 'ef'}-${id}`) : undefined
}
const sections: Record<string, string> = {
  arknightsRecruitment: 'ak-icon-recruit',
  arknightsOffice: 'ak-icon-hire',
  arknightsTraining: 'ak-icon-training',
  arknightsManufacturing: 'ak-icon-manufacture',
  arknightsDormitories: 'ak-icon-dormitory',
  arknightsClues: 'ak-icon-meeting',
  arknightsTrading: 'ak-icon-trading',
  arknightsSupport: 'ak-char',
  arknightsActivities: 'ak-logoRecord',
  arknightsRogueRelics: 'ak-logoExplore',
  arknightsRogueBank: 'ak-logoExplore',
  arknightsTower: 'ak-icon-towerRewardHigher',
  arknightsCampaign: 'ak-icon-campaignReward',
  arknightsSandbox: 'ak-logoBase',
  endfieldSpaceship: 'ef-spaceship',
  endfieldExplorationPuzzles: 'ef-ether',
  endfieldExplorationChests: 'ef-chests',
  endfieldExplorationPieces: 'ef-pieces',
  endfieldExplorationBlackboxes: 'ef-blackboxes',
  endfieldExplorationEquipChests: 'ef-equipChests',
  endfieldExplorationTrstars: 'ef-trstars',
  endfieldWarEchoes: 'ef-warEchoes',
  endfieldWarEchoesWeeks: 'ef-warEchoes',
  endfieldWarEchoesStages: 'ef-warEchoes',
  endfieldMonolith: 'ef-monolith',
}
export const sectionArt = (key: string) => (sections[key] ? art(sections[key]!) : undefined)
const rooms: Record<string, string> = {
  endfieldControl: 'control',
  endfieldManufacture1: 'manufacture',
  endfieldManufacture2: 'manufacture',
  endfieldManufacture: 'manufacture',
  endfieldPlant1: 'plant',
  endfieldPlant: 'plant',
  endfieldReception: 'reception',
}
type SectionItem = NonNullable<GameOverview['sections']>[number]['items'][number]
export function facilityArt(
  section: string,
  item: Pick<SectionItem, 'id' | 'nameKey' | 'operatorId'>,
) {
  if (item.operatorId) return undefined
  if (section === 'endfieldSpaceship')
    return rooms[item.nameKey ?? ''] ? art(`ef-${rooms[item.nameKey!]}`) : undefined
  if (section.startsWith('endfieldExploration')) {
    const id = item.id.split(':')[1]
    // indie_dg007 shares the official map02_lv004 artwork; unknown IDs remain text-only.
    return id ? art(`ef-${id === 'indie_dg007' ? 'map02_lv004' : id}`, 'map') : undefined
  }
  if (section === 'endfieldDomains' || section === 'endfieldSettlements') {
    const id = item.id.split(':')[0]
    return id === 'domain_1' || id === 'domain_2' ? art(`ef-${id}`, 'landscape') : undefined
  }
  return sectionArt(section)
}
